[tool.poetry]
name = "layer-3"
version = "0.1.0"
description = ""
authors = ["Matt SÃ¡rdi <sardi.matt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyautogui = "^0.9.54"
transformers = "^4.35.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
